version: "3.5"
services:
  desafio-back-end:
    container_name: desafio-back-end
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - postgres
    # networks:
    #   - app
    links:
      - postgres
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: user
      POSTGRES_DB: escola
